name: CI on Release

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

permissions:
  contents: read

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm install
      - run: npm install -g htmlhint stylelint stylelint-config-standard

      - run: htmlhint "src/**/*.html" .htmlhintrc
      - run: npx parcel build src/index.html --dist-dir dist
